apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: go-k-s
build:
  artifacts:
    - image: superjugger88/go
      context: .
      docker:
        dockerfile: pkg/Dockerfile.backend
deploy:
  helm:
    releases:
      - name: demo
        chartPath: charts/backend
        valuesFiles:
          - charts/backend/values.yaml
        version: 0.1.0
      - name: db
        chartPath: charts/db
        valuesFiles:
          - charts/db/values.yaml
        version: 0.1.0
