apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: go-k8s
build:
  artifacts:
    - image: superjugger88/go
      context: .
      docker:
        dockerfile: docker/Dockerfile.api
deploy:
  helm:
    releases:
      - name: db
        chartPath: charts/db
        valuesFiles:
          - charts/db/values.yaml
        version: 0.1.0
      - name: api
        chartPath: charts/api
        valuesFiles:
          - charts/api/values.yaml
        version: 0.1.0