apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: kubetraining
deploy:
  helm:
    releases:
      - name: demo
        chartPath: helm
        valuesFiles:
          - helm/values.yaml
        version: 0.1.0
