FROM golang:1.21.0-alpine AS builder

WORKDIR /app

COPY stonewall-api/ .
RUN go mod tidy
RUN go mod vendor

RUN  go build -mod vendor -o main

FROM golang:1.21.0-alpine

WORKDIR /srv

COPY --from=builder /app/main .

EXPOSE 8081

ENTRYPOINT ["./main"]